# Generated by Django 4.2.8 on 2025-05-16 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('married', 'Married'), ('unmarried', 'Unmarried')], max_length=10, null=True)),
                ('qualification', models.CharField(blank=True, choices=[('MD', 'Doctor of Medicine (MD)'), ('MBBS', 'Bachelor of Medicine, Bachelor of Surgery (MBBS)'), ('BDS', 'Bachelor of Dental Surgery (BDS)'), ('MS', 'Master of Surgery (MS)'), ('PHD', 'Doctor of Philosophy (PhD)')], max_length=30, null=True)),
                ('designation', models.CharField(blank=True, choices=[('SENIOR_DOCTOR', 'Senior Doctor'), ('JUNIOR_DOCTOR', 'Junior Doctor'), ('CONSULTANT', 'Consultant'), ('SPECIALIST', 'Specialist'), ('RESIDENT_DOCTOR', 'Resident Doctor')], max_length=255, null=True)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('B+', 'B+'), ('O+', 'O+'), ('AB+', 'AB+'), ('A-', 'A-'), ('B-', 'B-'), ('O-', 'O-'), ('AB-', 'AB-')], max_length=10, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('country', models.CharField(blank=True, choices=[('bangladesh', 'Bangladesh'), ('india', 'India'), ('china', 'China')], default='bangladesh', max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='departments.department')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
